<?php
$data = array (
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '家具',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '家具',
  ),
  10 => 
  array (
    'cat_id' => '10',
    'cat_name' => '定制家具',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '10',
    'name' => '定制家具',
  ),
  42 => 
  array (
    'cat_id' => '42',
    'cat_name' => '定制书柜/书台',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '42',
    'name' => '定制书柜/书台',
  ),
  41 => 
  array (
    'cat_id' => '41',
    'cat_name' => '定制橱柜',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '41',
    'name' => '定制橱柜',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '书房',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '7',
    'name' => '书房',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => '书柜/书架',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '33',
    'name' => '书柜/书架',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '书椅/转椅',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '34',
    'name' => '书椅/转椅',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => '书桌/工作台',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '32',
    'name' => '书桌/工作台',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '卧室',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '4',
    'name' => '卧室',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '床',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 2,
    'id' => '23',
    'name' => '床',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '床垫',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '24',
    'name' => '床垫',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '床头柜',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '25',
    'name' => '床头柜',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '儿童房',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '8',
    'name' => '儿童房',
  ),
  36 => 
  array (
    'cat_id' => '36',
    'cat_name' => '儿童床头柜',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '36',
    'name' => '儿童床头柜',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => '儿童衣柜',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '37',
    'name' => '儿童衣柜',
  ),
  35 => 
  array (
    'cat_id' => '35',
    'cat_name' => '儿童床',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '35',
    'name' => '儿童床',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '客厅',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '5',
    'name' => '客厅',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '沙发',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '26',
    'name' => '沙发',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '茶几/边桌',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '27',
    'name' => '茶几/边桌',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '电视柜',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '28',
    'name' => '电视柜',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '户外家具',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '9',
    'name' => '户外家具',
  ),
  39 => 
  array (
    'cat_id' => '39',
    'cat_name' => '休闲桌',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '39',
    'name' => '休闲桌',
  ),
  40 => 
  array (
    'cat_id' => '40',
    'cat_name' => '休闲椅',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '40',
    'name' => '休闲椅',
  ),
  38 => 
  array (
    'cat_id' => '38',
    'cat_name' => '吊篮/吊椅',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '38',
    'name' => '吊篮/吊椅',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '餐厅',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '6',
    'name' => '餐厅',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '餐桌',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '29',
    'name' => '餐桌',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '餐椅',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '30',
    'name' => '餐椅',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '餐边柜',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '31',
    'name' => '餐边柜',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '建材城',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '2',
    'name' => '建材城',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '卫浴用品',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '13',
    'name' => '卫浴用品',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '五金电器',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '14',
    'name' => '五金电器',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '灯饰照明',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '11',
    'name' => '灯饰照明',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '墙地面',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '15',
    'name' => '墙地面',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '厨房用品',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '12',
    'name' => '厨房用品',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '五金工具',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '16',
    'name' => '五金工具',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '家居家饰',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => '1',
    'level' => 0,
    'id' => '3',
    'name' => '家居家饰',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '家居饰品',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '20',
    'name' => '家居饰品',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '床上用品',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '17',
    'name' => '床上用品',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '厨房餐饮',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '21',
    'name' => '厨房餐饮',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '居家日用',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '18',
    'name' => '居家日用',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '生活电器',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '22',
    'name' => '生活电器',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '布艺织物',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '19',
    'name' => '布艺织物',
  ),
);
?>